### PR TITLE
Remove changelog

### PR DESCRIPTION
**Pull request by leo**
It looks like you haven't noticed this yet, so I'd like to let you know that changelog versions shouldn't be added to a separate file. But rather to the [releases](https://github.com/fv0/native-ui/releases).

To add some notes to a certain version, just click on it and an then choose "Edit" (I'm not sure if that's the correct position of the button, but I guess you'll figure it out). [Here](https://github.com/blog/1547-release-your-software)'s more on this.

I'm sure you've probably already noticed that GH automatically creates a new release each time you update the theme, so it's much cleaner to add the notes on those. :blush:

### CODE REVIEW

**Comment by fv0** [comment]
I added the seperate `CHANGELOG.md` file to make the "Changelog" button appear when you open the theme in Atom. The built in Github feature is nice, but is it really a bad practice? I could support both features.

screen shot 2016-01-17 at 15 37 34

**Comment by leo** [comment]
https://github.com/atom/atom/issues/10467

**Comment by leo** [comment]
@fv0 I'd say support both for now. :blush: https://github.com/atom/atom/issues/3705

**Comment by fv0** [comment]
Cool, thanks for looking that up.

**Pull request closed without merging**
